# The proper term is pseudo_replica_mode, but we use this compatibility alias
# to make the statement usable on server versions 8.0.24 and older.
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=1*/;
/*!50003 SET @OLD_COMPLETION_TYPE=@@COMPLETION_TYPE,COMPLETION_TYPE=0*/;
DELIMITER /*!*/;
# at 4
#221209 23:33:07 server id 1  end_log_pos 126 CRC32 0x4d3a0658 	Start: binlog v 4, server v 8.0.28 created 221209 23:33:07
BINLOG '
ExqUYw8BAAAAegAAAH4AAAAAAAQAOC4wLjI4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
AAAAAAAAAAAAAAAAAAAAAAAAEwANAAgAAAAABAAEAAAAYgAEGggAAAAICAgCAAAACgoKKioAEjQA
CigAAVgGOk0=
'/*!*/;
# at 126
#221209 23:33:07 server id 1  end_log_pos 157 CRC32 0x9cf51b8e 	Previous-GTIDs
# [empty]
# at 157
#221209 23:33:26 server id 1  end_log_pos 234 CRC32 0xdbf5057a 	Anonymous_GTID	last_committed=0	sequence_number=1	rbr_only=no	original_committed_timestamp=1670650406928927	immediate_commit_timestamp=1670650406928927	transaction_length=230
# original_commit_timestamp=1670650406928927 (2022-12-09 23:33:26.928927 Hora estándar, América Central)
# immediate_commit_timestamp=1670650406928927 (2022-12-09 23:33:26.928927 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650406928927*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 234
#221209 23:33:26 server id 1  end_log_pos 387 CRC32 0xcd733816 	Query	thread_id=9	exec_time=0	error_code=0	Xid = 2998
SET TIMESTAMP=1670650406/*!*/;
SET @@session.pseudo_thread_id=9/*!*/;
SET @@session.foreign_key_checks=1, @@session.sql_auto_is_null=0, @@session.unique_checks=1, @@session.autocommit=1/*!*/;
SET @@session.sql_mode=1075838976/*!*/;
SET @@session.auto_increment_increment=1, @@session.auto_increment_offset=1/*!*/;
/*!\C utf8mb4 *//*!*/;
SET @@session.character_set_client=255,@@session.collation_connection=255,@@session.collation_server=255/*!*/;
SET @@session.lc_time_names=0/*!*/;
SET @@session.collation_database=DEFAULT/*!*/;
/*!80011 SET @@session.default_collation_for_utf8mb4=255*//*!*/;
drop database IF EXISTS clinica_medica_p1
/*!*/;
# at 387
#221209 23:33:29 server id 1  end_log_pos 464 CRC32 0x2b737cc2 	Anonymous_GTID	last_committed=1	sequence_number=2	rbr_only=no	original_committed_timestamp=1670650409729335	immediate_commit_timestamp=1670650409729335	transaction_length=224
# original_commit_timestamp=1670650409729335 (2022-12-09 23:33:29.729335 Hora estándar, América Central)
# immediate_commit_timestamp=1670650409729335 (2022-12-09 23:33:29.729335 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650409729335*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 464
#221209 23:33:29 server id 1  end_log_pos 611 CRC32 0x2d443154 	Query	thread_id=9	exec_time=0	error_code=0	Xid = 3000
SET TIMESTAMP=1670650409/*!*/;
/*!80016 SET @@session.default_table_encryption=0*//*!*/;
create database clinica_medica_p1
/*!*/;
# at 611
#221209 23:34:37 server id 1  end_log_pos 688 CRC32 0xf5a98f4a 	Anonymous_GTID	last_committed=2	sequence_number=3	rbr_only=no	original_committed_timestamp=1670650477978485	immediate_commit_timestamp=1670650477978485	transaction_length=239
# original_commit_timestamp=1670650477978485 (2022-12-09 23:34:37.978485 Hora estándar, América Central)
# immediate_commit_timestamp=1670650477978485 (2022-12-09 23:34:37.978485 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650477978485*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 688
#221209 23:34:37 server id 1  end_log_pos 850 CRC32 0xb6ec1356 	Query	thread_id=62	exec_time=0	error_code=0
use `clinica_medica_p1`/*!*/;
SET TIMESTAMP=1670650477/*!*/;
SET @@session.pseudo_thread_id=62/*!*/;
SET @@session.foreign_key_checks=0, @@session.unique_checks=0/*!*/;
SET @@session.sql_mode=524288/*!*/;
DROP TABLE IF EXISTS `habitacion` /* generated by server */
/*!*/;
# at 850
#221209 23:34:38 server id 1  end_log_pos 929 CRC32 0x4b06aa11 	Anonymous_GTID	last_committed=3	sequence_number=4	rbr_only=no	original_committed_timestamp=1670650479874270	immediate_commit_timestamp=1670650479874270	transaction_length=390
# original_commit_timestamp=1670650479874270 (2022-12-09 23:34:39.874270 Hora estándar, América Central)
# immediate_commit_timestamp=1670650479874270 (2022-12-09 23:34:39.874270 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650479874270*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 929
#221209 23:34:38 server id 1  end_log_pos 1240 CRC32 0xcb8c5efe 	Query	thread_id=62	exec_time=1	error_code=0	Xid = 3016
SET TIMESTAMP=1670650478/*!*/;
/*!\C utf8mb3 *//*!*/;
SET @@session.character_set_client=33,@@session.collation_connection=255,@@session.collation_server=255/*!*/;
/*!80013 SET @@session.sql_require_primary_key=0*//*!*/;
CREATE TABLE `HABITACION` (
  `idHabitacion` int NOT NULL,
  `habitacion` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`idHabitacion`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
/*!*/;
# at 1240
#221209 23:34:40 server id 1  end_log_pos 1317 CRC32 0x4ed9ac39 	Anonymous_GTID	last_committed=4	sequence_number=5	rbr_only=no	original_committed_timestamp=1670650480116221	immediate_commit_timestamp=1670650480116221	transaction_length=240
# original_commit_timestamp=1670650480116221 (2022-12-09 23:34:40.116221 Hora estándar, América Central)
# immediate_commit_timestamp=1670650480116221 (2022-12-09 23:34:40.116221 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650480116221*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 1317
#221209 23:34:40 server id 1  end_log_pos 1480 CRC32 0x54fa486b 	Query	thread_id=62	exec_time=0	error_code=0	Xid = 3019
SET TIMESTAMP=1670650480/*!*/;
/*!\C utf8mb4 *//*!*/;
SET @@session.character_set_client=255,@@session.collation_connection=255,@@session.collation_server=255/*!*/;
/*!80013 SET @@session.sql_require_primary_key=0*//*!*/;
/*!40000 ALTER TABLE `HABITACION` DISABLE KEYS */
/*!*/;
# at 1480
#221209 23:34:40 server id 1  end_log_pos 1559 CRC32 0x56972704 	Anonymous_GTID	last_committed=5	sequence_number=6	rbr_only=yes	original_committed_timestamp=1670650480212922	immediate_commit_timestamp=1670650480212922	transaction_length=702
/*!50718 SET TRANSACTION ISOLATION LEVEL READ COMMITTED*//*!*/;
# original_commit_timestamp=1670650480212922 (2022-12-09 23:34:40.212922 Hora estándar, América Central)
# immediate_commit_timestamp=1670650480212922 (2022-12-09 23:34:40.212922 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650480212922*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 1559
#221209 23:34:40 server id 1  end_log_pos 1647 CRC32 0x3b048032 	Query	thread_id=62	exec_time=0	error_code=0
SET TIMESTAMP=1670650480/*!*/;
BEGIN
/*!*/;
# at 1647
#221209 23:34:40 server id 1  end_log_pos 1724 CRC32 0xee1ff578 	Table_map: `clinica_medica_p1`.`habitacion` mapped to number 236
# at 1724
#221209 23:34:40 server id 1  end_log_pos 2151 CRC32 0x68efa599 	Write_rows: table id 236 flags: STMT_END_F

BINLOG '
cBqUYxMBAAAATQAAALwGAAAAAOwAAAAAAAEAEWNsaW5pY2FfbWVkaWNhX3AxAApoYWJpdGFjaW9u
AAIDDwLIAAIBAQACA/z/AHj1H+4=
cBqUYx4BAAAAqwEAAGcIAAAAAOwAAAAAAAcAAgAC/wABAAAAElNhbGEgZGUgZXhhbWVuZXMgMQAC
AAAAElNhbGEgZGUgZXhhbWVuZXMgMgADAAAAElNhbGEgZGUgZXhhbWVuZXMgMwAEAAAAElNhbGEg
ZGUgZXhhbWVuZXMgNAAFAAAAElNhbGEgZGUgaW1hZ2VuZXMgMQAGAAAAGFNhbGEgZGUgcHJvY2Vk
aW1pZW50b3MgMQAHAAAAGFNhbGEgZGUgcHJvY2VkaW1pZW50b3MgMgAIAAAAGFNhbGEgZGUgcHJv
Y2VkaW1pZW50b3MgMwAJAAAAGFNhbGEgZGUgcHJvY2VkaW1pZW50b3MgNAAKAAAACVJlY2VwY2lv
bgALAAAAC0xhYm9yYXRvcmlvAAwAAAAYRXN0YWNpw7NuIGRlIHJldmlzacOzbiAxAA0AAAAYRXN0
YWNpw7NuIGRlIHJldmlzacOzbiAyAA4AAAAYRXN0YWNpw7NuIGRlIHJldmlzacOzbiAzAA8AAAAY
RXN0YWNpw7NuIGRlIHJldmlzacOzbiA0maXvaA==
'/*!*/;
# at 2151
#221209 23:34:40 server id 1  end_log_pos 2182 CRC32 0xfedba374 	Xid = 3020
COMMIT/*!*/;
# at 2182
#221209 23:34:40 server id 1  end_log_pos 2259 CRC32 0xa7835425 	Anonymous_GTID	last_committed=6	sequence_number=7	rbr_only=no	original_committed_timestamp=1670650480323416	immediate_commit_timestamp=1670650480323416	transaction_length=239
# original_commit_timestamp=1670650480323416 (2022-12-09 23:34:40.323416 Hora estándar, América Central)
# immediate_commit_timestamp=1670650480323416 (2022-12-09 23:34:40.323416 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650480323416*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 2259
#221209 23:34:40 server id 1  end_log_pos 2421 CRC32 0xdfed2d81 	Query	thread_id=62	exec_time=0	error_code=0	Xid = 3021
SET TIMESTAMP=1670650480/*!*/;
/*!80013 SET @@session.sql_require_primary_key=0*//*!*/;
/*!40000 ALTER TABLE `HABITACION` ENABLE KEYS */
/*!*/;
# at 2421
#221209 23:34:40 server id 1  end_log_pos 2498 CRC32 0xc50df492 	Anonymous_GTID	last_committed=7	sequence_number=8	rbr_only=no	original_committed_timestamp=1670650480358280	immediate_commit_timestamp=1670650480358280	transaction_length=242
# original_commit_timestamp=1670650480358280 (2022-12-09 23:34:40.358280 Hora estándar, América Central)
# immediate_commit_timestamp=1670650480358280 (2022-12-09 23:34:40.358280 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650480358280*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 2498
#221209 23:34:40 server id 1  end_log_pos 2663 CRC32 0xebcf366f 	Query	thread_id=62	exec_time=0	error_code=0
SET TIMESTAMP=1670650480/*!*/;
DROP TABLE IF EXISTS `log_actividad` /* generated by server */
/*!*/;
# at 2663
#221209 23:34:40 server id 1  end_log_pos 2742 CRC32 0xc9d0fa0e 	Anonymous_GTID	last_committed=8	sequence_number=9	rbr_only=no	original_committed_timestamp=1670650481241140	immediate_commit_timestamp=1670650481241140	transaction_length=899
# original_commit_timestamp=1670650481241140 (2022-12-09 23:34:41.241140 Hora estándar, América Central)
# immediate_commit_timestamp=1670650481241140 (2022-12-09 23:34:41.241140 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650481241140*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 2742
#221209 23:34:40 server id 1  end_log_pos 3562 CRC32 0x84cd0938 	Query	thread_id=62	exec_time=1	error_code=0	Xid = 3026
SET TIMESTAMP=1670650480/*!*/;
/*!\C utf8mb3 *//*!*/;
SET @@session.character_set_client=33,@@session.collation_connection=255,@@session.collation_server=255/*!*/;
/*!80013 SET @@session.sql_require_primary_key=0*//*!*/;
CREATE TABLE `LOG_ACTIVIDAD` (
  `id_log_actividad` int NOT NULL,
  `timestampx` varchar(100) NOT NULL,
  `actividad` varchar(500) NOT NULL,
  `PACIENTE_idPaciente` int NOT NULL,
  `HABITACION_idHabitacion` int NOT NULL,
  PRIMARY KEY (`id_log_actividad`),
  KEY `LOG_ACTIVIDAD_HABITACION_null_fk` (`HABITACION_idHabitacion`),
  KEY `LOG_ACTIVIDAD_PACIENTE_null_fk` (`PACIENTE_idPaciente`),
  CONSTRAINT `LOG_ACTIVIDAD_HABITACION_null_fk` FOREIGN KEY (`HABITACION_idHabitacion`) REFERENCES `HABITACION` (`idHabitacion`),
  CONSTRAINT `LOG_ACTIVIDAD_PACIENTE_null_fk` FOREIGN KEY (`PACIENTE_idPaciente`) REFERENCES `PACIENTE` (`idPaciente`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
/*!*/;
# at 3562
#221209 23:34:41 server id 1  end_log_pos 3639 CRC32 0x9959b1f0 	Anonymous_GTID	last_committed=9	sequence_number=10	rbr_only=no	original_committed_timestamp=1670650481341159	immediate_commit_timestamp=1670650481341159	transaction_length=243
# original_commit_timestamp=1670650481341159 (2022-12-09 23:34:41.341159 Hora estándar, América Central)
# immediate_commit_timestamp=1670650481341159 (2022-12-09 23:34:41.341159 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650481341159*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 3639
#221209 23:34:41 server id 1  end_log_pos 3805 CRC32 0x11e50869 	Query	thread_id=62	exec_time=0	error_code=0	Xid = 3029
SET TIMESTAMP=1670650481/*!*/;
/*!\C utf8mb4 *//*!*/;
SET @@session.character_set_client=255,@@session.collation_connection=255,@@session.collation_server=255/*!*/;
/*!80013 SET @@session.sql_require_primary_key=0*//*!*/;
/*!40000 ALTER TABLE `LOG_ACTIVIDAD` DISABLE KEYS */
/*!*/;
# at 3805
#221209 23:34:41 server id 1  end_log_pos 3882 CRC32 0x3d7743ca 	Anonymous_GTID	last_committed=10	sequence_number=11	rbr_only=no	original_committed_timestamp=1670650481397350	immediate_commit_timestamp=1670650481397350	transaction_length=242
# original_commit_timestamp=1670650481397350 (2022-12-09 23:34:41.397350 Hora estándar, América Central)
# immediate_commit_timestamp=1670650481397350 (2022-12-09 23:34:41.397350 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650481397350*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 3882
#221209 23:34:41 server id 1  end_log_pos 4047 CRC32 0x661d6d67 	Query	thread_id=62	exec_time=0	error_code=0	Xid = 3030
SET TIMESTAMP=1670650481/*!*/;
/*!80013 SET @@session.sql_require_primary_key=0*//*!*/;
/*!40000 ALTER TABLE `LOG_ACTIVIDAD` ENABLE KEYS */
/*!*/;
# at 4047
#221209 23:34:41 server id 1  end_log_pos 4124 CRC32 0x0f781249 	Anonymous_GTID	last_committed=11	sequence_number=12	rbr_only=no	original_committed_timestamp=1670650481430220	immediate_commit_timestamp=1670650481430220	transaction_length=243
# original_commit_timestamp=1670650481430220 (2022-12-09 23:34:41.430220 Hora estándar, América Central)
# immediate_commit_timestamp=1670650481430220 (2022-12-09 23:34:41.430220 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650481430220*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 4124
#221209 23:34:41 server id 1  end_log_pos 4290 CRC32 0x0611daf3 	Query	thread_id=62	exec_time=0	error_code=0
SET TIMESTAMP=1670650481/*!*/;
DROP TABLE IF EXISTS `log_habitacion` /* generated by server */
/*!*/;
# at 4290
#221209 23:34:41 server id 1  end_log_pos 4369 CRC32 0x32215bb1 	Anonymous_GTID	last_committed=12	sequence_number=13	rbr_only=no	original_committed_timestamp=1670650481938192	immediate_commit_timestamp=1670650481938192	transaction_length=623
# original_commit_timestamp=1670650481938192 (2022-12-09 23:34:41.938192 Hora estándar, América Central)
# immediate_commit_timestamp=1670650481938192 (2022-12-09 23:34:41.938192 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650481938192*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 4369
#221209 23:34:41 server id 1  end_log_pos 4913 CRC32 0x56d77577 	Query	thread_id=62	exec_time=0	error_code=0	Xid = 3035
SET TIMESTAMP=1670650481/*!*/;
/*!\C utf8mb3 *//*!*/;
SET @@session.character_set_client=33,@@session.collation_connection=255,@@session.collation_server=255/*!*/;
/*!80013 SET @@session.sql_require_primary_key=0*//*!*/;
CREATE TABLE `LOG_HABITACION` (
  `timestampx` varchar(100) NOT NULL,
  `statusx` varchar(45) NOT NULL,
  `idHabitacion` int DEFAULT NULL,
  PRIMARY KEY (`timestampx`),
  KEY `LOG_HABITACION_HABITACION_idHabitacion_fk` (`idHabitacion`),
  CONSTRAINT `LOG_HABITACION_HABITACION_idHabitacion_fk` FOREIGN KEY (`idHabitacion`) REFERENCES `HABITACION` (`idHabitacion`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
/*!*/;
# at 4913
#221209 23:34:42 server id 1  end_log_pos 4990 CRC32 0x3fe881ab 	Anonymous_GTID	last_committed=13	sequence_number=14	rbr_only=no	original_committed_timestamp=1670650482097514	immediate_commit_timestamp=1670650482097514	transaction_length=244
# original_commit_timestamp=1670650482097514 (2022-12-09 23:34:42.097514 Hora estándar, América Central)
# immediate_commit_timestamp=1670650482097514 (2022-12-09 23:34:42.097514 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650482097514*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 4990
#221209 23:34:42 server id 1  end_log_pos 5157 CRC32 0x19c9bd1a 	Query	thread_id=62	exec_time=0	error_code=0	Xid = 3038
SET TIMESTAMP=1670650482/*!*/;
/*!\C utf8mb4 *//*!*/;
SET @@session.character_set_client=255,@@session.collation_connection=255,@@session.collation_server=255/*!*/;
/*!80013 SET @@session.sql_require_primary_key=0*//*!*/;
/*!40000 ALTER TABLE `LOG_HABITACION` DISABLE KEYS */
/*!*/;
# at 5157
#221209 23:34:42 server id 1  end_log_pos 5234 CRC32 0xe12ee8e4 	Anonymous_GTID	last_committed=14	sequence_number=15	rbr_only=no	original_committed_timestamp=1670650482161817	immediate_commit_timestamp=1670650482161817	transaction_length=243
# original_commit_timestamp=1670650482161817 (2022-12-09 23:34:42.161817 Hora estándar, América Central)
# immediate_commit_timestamp=1670650482161817 (2022-12-09 23:34:42.161817 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650482161817*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 5234
#221209 23:34:42 server id 1  end_log_pos 5400 CRC32 0x0a703c5f 	Query	thread_id=62	exec_time=0	error_code=0	Xid = 3039
SET TIMESTAMP=1670650482/*!*/;
/*!80013 SET @@session.sql_require_primary_key=0*//*!*/;
/*!40000 ALTER TABLE `LOG_HABITACION` ENABLE KEYS */
/*!*/;
# at 5400
#221209 23:34:42 server id 1  end_log_pos 5477 CRC32 0x7951882d 	Anonymous_GTID	last_committed=15	sequence_number=16	rbr_only=no	original_committed_timestamp=1670650482281772	immediate_commit_timestamp=1670650482281772	transaction_length=237
# original_commit_timestamp=1670650482281772 (2022-12-09 23:34:42.281772 Hora estándar, América Central)
# immediate_commit_timestamp=1670650482281772 (2022-12-09 23:34:42.281772 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650482281772*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 5477
#221209 23:34:42 server id 1  end_log_pos 5637 CRC32 0xecbca4ce 	Query	thread_id=62	exec_time=0	error_code=0
SET TIMESTAMP=1670650482/*!*/;
DROP TABLE IF EXISTS `paciente` /* generated by server */
/*!*/;
# at 5637
#221209 23:34:42 server id 1  end_log_pos 5716 CRC32 0xdaa9b9c6 	Anonymous_GTID	last_committed=16	sequence_number=17	rbr_only=no	original_committed_timestamp=1670650482858763	immediate_commit_timestamp=1670650482858763	transaction_length=399
# original_commit_timestamp=1670650482858763 (2022-12-09 23:34:42.858763 Hora estándar, América Central)
# immediate_commit_timestamp=1670650482858763 (2022-12-09 23:34:42.858763 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650482858763*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 5716
#221209 23:34:42 server id 1  end_log_pos 6036 CRC32 0x9c6a2185 	Query	thread_id=62	exec_time=0	error_code=0	Xid = 3044
SET TIMESTAMP=1670650482/*!*/;
/*!\C utf8mb3 *//*!*/;
SET @@session.character_set_client=33,@@session.collation_connection=255,@@session.collation_server=255/*!*/;
/*!80013 SET @@session.sql_require_primary_key=0*//*!*/;
CREATE TABLE `PACIENTE` (
  `idPaciente` int NOT NULL,
  `edad` int NOT NULL,
  `genero` varchar(20) NOT NULL,
  PRIMARY KEY (`idPaciente`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
/*!*/;
# at 6036
#221209 23:34:43 server id 1  end_log_pos 6113 CRC32 0x7ac90fda 	Anonymous_GTID	last_committed=17	sequence_number=18	rbr_only=no	original_committed_timestamp=1670650483024888	immediate_commit_timestamp=1670650483024888	transaction_length=238
# original_commit_timestamp=1670650483024888 (2022-12-09 23:34:43.024888 Hora estándar, América Central)
# immediate_commit_timestamp=1670650483024888 (2022-12-09 23:34:43.024888 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650483024888*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 6113
#221209 23:34:43 server id 1  end_log_pos 6274 CRC32 0x079bf7f7 	Query	thread_id=62	exec_time=0	error_code=0	Xid = 3047
SET TIMESTAMP=1670650483/*!*/;
/*!\C utf8mb4 *//*!*/;
SET @@session.character_set_client=255,@@session.collation_connection=255,@@session.collation_server=255/*!*/;
/*!80013 SET @@session.sql_require_primary_key=0*//*!*/;
/*!40000 ALTER TABLE `PACIENTE` DISABLE KEYS */
/*!*/;
# at 6274
#221209 23:34:43 server id 1  end_log_pos 6351 CRC32 0x38b73fec 	Anonymous_GTID	last_committed=18	sequence_number=19	rbr_only=no	original_committed_timestamp=1670650483124209	immediate_commit_timestamp=1670650483124209	transaction_length=237
# original_commit_timestamp=1670650483124209 (2022-12-09 23:34:43.124209 Hora estándar, América Central)
# immediate_commit_timestamp=1670650483124209 (2022-12-09 23:34:43.124209 Hora estándar, América Central)
/*!80001 SET @@session.original_commit_timestamp=1670650483124209*//*!*/;
/*!80014 SET @@session.original_server_version=80028*//*!*/;
/*!80014 SET @@session.immediate_server_version=80028*//*!*/;
SET @@SESSION.GTID_NEXT= 'ANONYMOUS'/*!*/;
# at 6351
#221209 23:34:43 server id 1  end_log_pos 6511 CRC32 0xd456c434 	Query	thread_id=62	exec_time=0	error_code=0	Xid = 3048
SET TIMESTAMP=1670650483/*!*/;
/*!80013 SET @@session.sql_require_primary_key=0*//*!*/;
/*!40000 ALTER TABLE `PACIENTE` ENABLE KEYS */
/*!*/;
# at 6511
#221209 23:35:15 server id 1  end_log_pos 6561 CRC32 0x77e8b57c 	Rotate to ORELLANA-bin.000882  pos: 4
SET @@SESSION.GTID_NEXT= 'AUTOMATIC' /* added by mysqlbinlog */ /*!*/;
DELIMITER ;
# End of log file
/*!50003 SET COMPLETION_TYPE=@OLD_COMPLETION_TYPE*/;
/*!50530 SET @@SESSION.PSEUDO_SLAVE_MODE=0*/;
